name: Quality + Sync GitLab

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["**"]

jobs:
  quality-backend:
    name: Backend - Tests & Sonar
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # requis pour Sonar

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Tests unitaires & tests d'intégration
      - name: Run backend tests (unit + IT) with coverage
        run: mvn -B clean verify

      - name: SonarCloud Scan (Backend)
        if: github.ref == 'refs/heads/main'
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=pololac_powerme_back \
          -Dsonar.organization=pololac \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        continue-on-error: true # Rend le Quality Gate non bloquant
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pour PR decoration

  quality-frontend:
    name: Frontend - Tests & SonarCloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
          echo "CHROME_BIN=/usr/bin/chromium" >> $GITHUB_ENV

      - name: Run frontend tests with coverage
        run: npm run test:ci

      - name: SonarCloud Scan (Frontend)
        # Limite l'analyse Sonar à la branche main
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true #Rend le Quality Gate non bloquant
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.projectKey=pololac_powerme_front
            -Dsonar.organization=pololac

  sync-gitlab:
    name: Sync to GitLab
    runs-on: ubuntu-latest

    needs:
      - quality-backend
      - quality-frontend

    # Exécute uniquement si :
    # - push sur main
    # - pull_request vers main
    if: |
      false &&
      success() &&
      (
        (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
        (github.event_name == 'pull_request' && github.base_ref == 'main')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
          force_push: true
